title: Git Extensions
description: Git Extensions is a standalone UI tool for managing Git repositories
google_analytics: UA-46578757-1
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
